[de MODULE_INFO
  ("name"      "network-setup.l")
  ("version"   "4.4.0")
  ("summary"   "Read and configure network settings (IPv4/IPv6) - Trial version")
  ("source"    "https://github.com/on-prem/console-gui")
  ("author"    "Alexander Williams")
  ("license"   "MPL-2.0")
  ("copyright" "(c) 2018 Alexander Williams, Unscramble <license@unscramble.jp>")
  ("requires"
    ("jidoteki-admin"    "v1.20.0"    "https://github.com/on-prem/jidoteki-admin.git") ]
